name       : haskell-unix-compat
version    : 0.4.3.1
release    : 1
source     :
    - http://hackage.haskell.org/package/unix-compat-0.4.3.1/unix-compat-0.4.3.1.tar.gz : 72801d5a654a6e108c153f412ebd54c37fb445643770e0b97701a59e109f7e27
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides portable implementations of parts of the unix package.
description: |
    This package provides portable implementations of parts of the unix package.
builddeps  :
    - haskell-cabal-install
    - haskell-old-time
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
