name       : haskell-unix-compat
version    : 0.5.2
release    : 5
source     :
    - https://hackage.haskell.org/package/unix-compat-0.5.2/unix-compat-0.5.2.tar.gz : 659a4e442f71505d45b0d0fb28a347aa1ac5e1f39feaea5d58e674e5d2ce0ba9
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides portable implementations of parts of the unix package.
description: |
    This package provides portable implementations of parts of the unix package.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
