name       : haskell-unix-compat
version    : 0.5.0.1
release    : 4
source     :
    - https://hackage.haskell.org/package/unix-compat-0.5.0.1/unix-compat-0.5.0.1.tar.gz : c2f299e0439c15d93d5700911c922fd2b35543c19ba053779cd52f3b051caebd
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides portable implementations of parts of the unix package.
description: |
    This package provides portable implementations of parts of the unix package.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
